spring:
  profiles:
    include: "oauth"
---
spring:
  config:
    activate:
      on-profile: test
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/idiot?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false #시작과 동시에 실행되는 건 방지
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: chosoyeon
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

---
spring:
  config:
    activate:
      on-profile: prod
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://idiot-root.c35pvkgak4n8.ap-northeast-2.rds.amazonaws.com:3306/idiot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: h13001212!
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  batch:
    job:
      enabled: false #시작과 동시에 실행되는 건 방지
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
logging:
  file:
    name: mylog.log
    path: /server/myapp/logs
---
spring:
  config:
    activate:
      on-profile: server
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://test-rds.c35pvkgak4n8.ap-northeast-2.rds.amazonaws.com:3306/idiot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: h13001212!
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  batch:
    job:
      enabled: false #시작과 동시에 실행되는 건 방지
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true